name: lhie1
on:
  schedule:
    - cron: '1 19 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: lhie1 
jobs: 
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: lhie1
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/lhie1/Rules.git"
          source_branch: "master"
          destination_branch: "lhie1"
          github_token: ${{ secrets.PAT }}
