name: Wenmoux
on:
  schedule:
    - cron: '1 12 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: Wenmoux
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Wenmoux
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/Wenmoux/scripts.git"
          source_branch: "wen"
          destination_branch: "Wenmoux"
          github_token: ${{ secrets.PAT }}
